[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
startup_mode = "Windowed"

decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 7.0

[colors.primary]
background = "#1b1825"
foreground = "#f2f0f5"
dim_foreground = "#7e7890"

[colors.normal]
black   = "#1b1825"
red     = "#f55555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#4396ff"
magenta = "#ff79c6"
cyan    = "#4bf3ff"
white   = "#f2f0f5"

[colors.bright]
black   = "#7e7890"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#5fa7ff"
magenta = "#ff92df"
cyan    = "#6bf5ff"
white   = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
